require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PlaceBeensController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PlaceBeen. As you add validations to PlaceBeen, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlaceBeensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all place_beens as @place_beens" do
      place_been = PlaceBeen.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:place_beens)).to eq([place_been])
    end
  end

  describe "GET show" do
    it "assigns the requested place_been as @place_been" do
      place_been = PlaceBeen.create! valid_attributes
      get :show, {:id => place_been.to_param}, valid_session
      expect(assigns(:place_been)).to eq(place_been)
    end
  end

  describe "GET new" do
    it "assigns a new place_been as @place_been" do
      get :new, {}, valid_session
      expect(assigns(:place_been)).to be_a_new(PlaceBeen)
    end
  end

  describe "GET edit" do
    it "assigns the requested place_been as @place_been" do
      place_been = PlaceBeen.create! valid_attributes
      get :edit, {:id => place_been.to_param}, valid_session
      expect(assigns(:place_been)).to eq(place_been)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlaceBeen" do
        expect {
          post :create, {:place_been => valid_attributes}, valid_session
        }.to change(PlaceBeen, :count).by(1)
      end

      it "assigns a newly created place_been as @place_been" do
        post :create, {:place_been => valid_attributes}, valid_session
        expect(assigns(:place_been)).to be_a(PlaceBeen)
        expect(assigns(:place_been)).to be_persisted
      end

      it "redirects to the created place_been" do
        post :create, {:place_been => valid_attributes}, valid_session
        expect(response).to redirect_to(PlaceBeen.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved place_been as @place_been" do
        post :create, {:place_been => invalid_attributes}, valid_session
        expect(assigns(:place_been)).to be_a_new(PlaceBeen)
      end

      it "re-renders the 'new' template" do
        post :create, {:place_been => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested place_been" do
        place_been = PlaceBeen.create! valid_attributes
        put :update, {:id => place_been.to_param, :place_been => new_attributes}, valid_session
        place_been.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested place_been as @place_been" do
        place_been = PlaceBeen.create! valid_attributes
        put :update, {:id => place_been.to_param, :place_been => valid_attributes}, valid_session
        expect(assigns(:place_been)).to eq(place_been)
      end

      it "redirects to the place_been" do
        place_been = PlaceBeen.create! valid_attributes
        put :update, {:id => place_been.to_param, :place_been => valid_attributes}, valid_session
        expect(response).to redirect_to(place_been)
      end
    end

    describe "with invalid params" do
      it "assigns the place_been as @place_been" do
        place_been = PlaceBeen.create! valid_attributes
        put :update, {:id => place_been.to_param, :place_been => invalid_attributes}, valid_session
        expect(assigns(:place_been)).to eq(place_been)
      end

      it "re-renders the 'edit' template" do
        place_been = PlaceBeen.create! valid_attributes
        put :update, {:id => place_been.to_param, :place_been => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested place_been" do
      place_been = PlaceBeen.create! valid_attributes
      expect {
        delete :destroy, {:id => place_been.to_param}, valid_session
      }.to change(PlaceBeen, :count).by(-1)
    end

    it "redirects to the place_beens list" do
      place_been = PlaceBeen.create! valid_attributes
      delete :destroy, {:id => place_been.to_param}, valid_session
      expect(response).to redirect_to(place_beens_url)
    end
  end

end
